app = "biblio-api"
primary_region = "arn"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "R -e 'pr <- plumber::pr('biblio-api\plumber.R'); pr$run(host='0.0.0.0', port=8000)'"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
