# fly.toml app configuration file generated for biblio-api on 2025-04-02T13:36:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biblio-api"
primary_region = "arn"

[build]
  image = "rocker/r-ver:4.3.1"

[env]
  PORT = "8000"
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "R -e \"pr <- plumber::pr('plumber.R'); pr$run(host='0.0.0.0', port=8000)\""

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
