name: Deploy to Fly.io

on:
  push:
    branches:
      - main # Automatically run on push to main
  workflow_dispatch: # Enables manual triggering from GitHub UI

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy with Fly.io
        run: flyctl deploy --remote-only -a biblio-api
        working-directory: ./biblio-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
